name: reading_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  cloud_firestore: ^5.2.1
  firebase_core: ^3.3.0
  google_generative_ai: ^0.4.6
  path_provider: ^2.1.4
  retry: ^3.1.2
  firebase_auth: ^5.1.4
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/test_data.json
    - assets/conversation_prompt.txt
    - assets/note_prompt.txt
    - assets/images/logo_google.svg
